# Generated by Django 4.0.6 on 2022-07-16 09:38

import ads.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_image_ad_ad_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(default=0, upload_to=ads.models.ad_author_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_images',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ads.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=0, upload_to=ads.models.ad_author_directory_path),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_files',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ads.file'),
        ),
    ]
