# Generated by Django 4.0.6 on 2022-07-16 10:35

import ads.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_file_author_image_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_files',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.file'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_images',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=0, upload_to=ads.models.ad_image_author_directory_path),
        ),
    ]
