# Generated by Django 4.0.6 on 2022-07-16 10:36

import ads.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_ad_files_alter_ad_ad_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.file'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.image'),
        ),
        migrations.AlterField(
            model_name='file',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.user'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=ads.models.ad_author_directory_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.user'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=ads.models.ad_image_author_directory_path),
        ),
    ]
