# Generated by Django 4.0.6 on 2022-07-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_ad_ad_files_alter_ad_ad_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.file'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.image'),
        ),
    ]
