# Generated by Django 4.0.6 on 2022-07-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ad_ad_files_alter_ad_ad_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ad_images',
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_images',
            field=models.ManyToManyField(blank=True, to='ads.image'),
        ),
    ]
