# Generated by Django 4.0.6 on 2022-07-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_remove_file_author_remove_image_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ad_files',
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_files',
            field=models.ManyToManyField(blank=True, to='ads.file'),
        ),
    ]
