# Generated by Django 4.0.6 on 2022-07-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
