# Generated by Django 4.0.6 on 2022-07-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_alter_ad_ad_author_alter_response_response_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-id']},
        ),
    ]
