# Generated by Django 4.0.6 on 2022-07-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_alter_response_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='ad',
            new_name='ad_response',
        ),
    ]
