# Generated by Django 4.0.6 on 2022-07-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_alter_myuser_birhtday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='birhtday',
        ),
    ]
